<?php
$this->db->query('ALTER TABLE `' . $this->db->dbprefix('nexo_articles') . '` ADD `SPECIAL_PRICE_START_DATE` DATETIME NOT NULL AFTER `AUTHOR`, ADD `SPECIAL_PRICE_END_DATE` DATETIME NOT NULL AFTER `SPECIAL_PRICE_START_DATE`;');
