<?php
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_articles') . '` 
	CHANGE `PRIX_DACHAT` `PRIX_DACHAT` FLOAT(11) NOT NULL,
	CHANGE `FRAIS_ACCESSOIRE` `FRAIS_ACCESSOIRE` FLOAT(11) NOT NULL,
	CHANGE `TAUX_DE_MARGE` `TAUX_DE_MARGE` FLOAT(11) NOT NULL,
	CHANGE `COUT_DACHAT` `COUT_DACHAT` FLOAT(11) NOT NULL,
	CHANGE `PRIX_DE_VENTE` `PRIX_DE_VENTE` FLOAT(11) NOT NULL,
	CHANGE `PRIX_PROMOTIONEL` `PRIX_PROMOTIONEL` FLOAT(11) NOT NULL;
');

// Customers
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_clients') . '` 
	CHANGE `TOTAL_SPEND` `TOTAL_SPEND` FLOAT(11) NOT NULL;
');

$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_clients_groups') . '` 
	CHANGE `DISCOUNT_AMOUNT` `DISCOUNT_AMOUNT` FLOAT(11) NOT NULL,
	CHANGE `DISCOUNT_PERCENT` `DISCOUNT_PERCENT` FLOAT(11) NOT NULL;
');

// Change Commandes
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_commandes') . '` 
	CHANGE `SOMME_PERCU` `SOMME_PERCU` FLOAT(11) NOT NULL,
	CHANGE `REMISE` `REMISE` FLOAT(11) NOT NULL,
	CHANGE `RABAIS` `RABAIS` FLOAT(11) NOT NULL,
	CHANGE `RISTOURNE` `RISTOURNE` FLOAT(11) NOT NULL,
	CHANGE `TOTAL` `TOTAL` FLOAT(11) NOT NULL,
	CHANGE `TVA` `TVA` FLOAT(11) NOT NULL,
	CHANGE `GROUP_DISCOUNT` `GROUP_DISCOUNT` FLOAT(11) NOT NULL;
');

// Change Commandes
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_commandes_produits') . '` 
	CHANGE `PRIX` `PRIX` FLOAT(11) NOT NULL,
	CHANGE `PRIX_TOTAL` `PRIX_TOTAL` FLOAT(11) NOT NULL;
');