<?php
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_articles') . '` 
	CHANGE `PRIX_DACHAT` `PRIX_DACHAT` FLOAT(11) NOT NULL,
	CHANGE `FRAIS_ACCESSOIRE` `FRAIS_ACCESSOIRE` FLOAT(11) NOT NULL,
	CHANGE `TAUX_DE_MARGE` `TAUX_DE_MARGE` FLOAT(11) NOT NULL,
	CHANGE `COUT_DACHAT` `COUT_DACHAT` FLOAT(11) NOT NULL,
	CHANGE `PRIX_DE_VENTE` `PRIX_DE_VENTE` FLOAT(11) NOT NULL,
	CHANGE `PRIX_PROMOTIONEL` `PRIX_PROMOTIONEL` FLOAT(11) NOT NULL;
');

// Change Commandes
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_commandes') . '` 
	CHANGE `PRIX_DACHAT` `PRIX_DACHAT` FLOAT(11) NOT NULL,
	CHANGE `FRAIS_ACCESSOIRE` `FRAIS_ACCESSOIRE` FLOAT(11) NOT NULL,
	CHANGE `TAUX_DE_MARGE` `TAUX_DE_MARGE` FLOAT(11) NOT NULL,
	CHANGE `COUT_DACHAT` `COUT_DACHAT` FLOAT(11) NOT NULL,
	CHANGE `PRIX_DE_VENTE` `PRIX_DE_VENTE` FLOAT(11) NOT NULL,
	CHANGE `PRIX_PROMOTIONEL` `PRIX_PROMOTIONEL` FLOAT(11) NOT NULL;
');