<?php
$this->db->query('
	ALTER TABLE `' . $this->db->dbprefix('nexo_clients') . '` 
	ADD `ADRESSE` text NOT NULL AFTER `DATE_NAISSANCE`,
	ADD `NBR_COMMANDES` int NOT NULL AFTER `ADRESSE`,
	ADD `OVERALL_COMMANDES` int NOT NULL AFTER `NBR_COMMANDES`,
	ADD `DISCOUNT_ACTIVE` int NOT NULL AFTER `OVERALL_COMMANDES`,
	ADD `TOTAL_SPEND` int NOT NULL AFTER `DISCOUNT_ACTIVE`,
	ADD `LAST_ORDER` varchar(200) NOT NULL AFTER `TOTAL_SPEND`,
	ADD `AVATAR` varchar(200) NOT NULL AFTER `LAST_ORDER`,
	ADD `STATE` varchar(200) NOT NULL AFTER `AVATAR`,
	ADD `CITY` varchar(200) NOT NULL AFTER `STATE`,
	ADD `POST_CODE` varchar(200) NOT NULL AFTER `CITY`,
	ADD `COUNTRY` varchar(200) NOT NULL AFTER `POST_CODE`,
	ADD `COMPANY_NAME` varchar(200) NOT NULL AFTER `COUNTRY`,
	ADD `DATE_CREATION` datetime NOT NULL AFTER `COMPANY_NAME`,
	ADD `DATE_MOD` datetime NOT NULL AFTER `DATE_CREATION`,
	ADD `AUTHOR` int NOT NULL AFTER `DATE_MOD`;
');